In [1]:
import pathlib
import tensorflow as tf
from tensorflow import keras


batch_size = 32
img_height = 180
img_width = 180

# How to load model
# https://www.tensorflow.org/guide/keras/save_and_serialize
model = keras.models.load_model("niceflowers.h5")

data_dir = "flowers/"
data_dir = pathlib.Path(data_dir)

seed = 100
test_ds =  keras.utils.image_dataset_from_directory(directory=data_dir, validation_split=0.0025, subset="validation", seed=seed, image_size=(img_height, img_width), batch_size=batch_size)


2022-05-11 21:33:35.578222: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-11 21:33:35.600783: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-11 21:33:35.600899: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-11 21:33:35.601564: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

Found 4317 files belonging to 5 classes.
Using 10 files for validation.


In [2]:
import numpy as np
predict_labels = model.predict(test_ds)
test_loss, test_acc = model.evaluate(test_ds)

test_labels = np.concatenate([y for x, y in test_ds], axis=0)

2022-05-11 21:33:37.201418: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8400


1/1 [==============================] - 0s 94ms/step - loss: 0.7208 - accuracy: 0.7000


2022-05-11 21:33:38.002298: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-05-11 21:33:38.091252: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [3]:
test_loss, test_acc

(0.7208430171012878, 0.699999988079071)

array([3, 3, 0, 0, 4, 4, 2, 1, 1, 2], dtype=int32)

In [5]:
predict_labels

array([[ 0.36298096,  1.6049823 , -1.3827306 ,  0.11617887, -0.9323068 ],
       [-2.3060648 , -1.7789037 ,  0.9818022 , -2.4124432 , -0.44804785],
       [-5.5425315 ,  7.131281  , -3.2036433 , -2.1446962 , -2.6621797 ],
       [-1.2341324 , -1.4106069 , -3.3458164 ,  3.3887057 , -1.0041548 ],
       [-4.6836233 , -8.470603  ,  1.703112  , -7.1972847 ,  0.90173495],
       [ 2.807904  ,  0.20952539, -1.3278158 , -1.4727125 , -1.0570748 ],
       [-2.1114287 ,  3.725607  , -0.5079544 , -2.3960807 , -1.9578418 ],
       [-5.3235946 , -8.111933  ,  2.2441258 , -7.383982  ,  0.2421122 ],
       [-1.2012829 ,  0.55370176,  0.6725384 , -2.4036317 , -0.98600096],
       [ 0.26604074,  0.19053349, -0.2253868 , -1.3952035 , -0.38092503]],
      dtype=float32)

In [22]:
print(test_labels)
ab = np.abs(predict_labels)
print([np.argmin(pp) for pp in ab])

[3 3 0 0 4 4 2 1 1 2]
[3, 4, 3, 4, 4, 1, 2, 4, 1, 1]
